"""
PERSONA V3 — PDF Generation Engine
===================================
Generates high-quality branded LinkedIn Profile PDF reports matching the web application design.
Includes:
  - Header with LinkedIn Blue banner
  - Profile summary with avatar download
  - Detailed sections for About, Current Position, Experience, Education,
    Skills (with endorsements), Certifications, Languages, Volunteer, Honors, Recommendations
  - Support for Single Profile, Bulk Profiles, and Raw Text exports
"""

import os
import re
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional
import requests
from fpdf import FPDF

from cleaner import clean_profile


def strip_emojis(text: str) -> str:
    """Remove emojis and special unicode symbols that crash standard PDF fonts."""
    if not text:
        return ""
    emoji_pattern = re.compile(
        "["
        "\U00010000-\U0010ffff"
        "\u2600-\u27BF"
        "\u2000-\u32FF"
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub(r"", str(text)).strip()


def make_pdf_safe(text: Any) -> str:
    """Sanitize text for latin-1 PDF output; returns empty string if blank/null."""
    if not text:
        return ""
    s = str(text)
    replacements = {
        "\u2014": " - ",  # em-dash
        "\u2013": "-",    # en-dash
        "\u201c": '"',    # left double quote
        "\u201d": '"',    # right double quote
        "\u2018": "'",    # left single quote
        "\u2019": "'",    # right single quote
        "\u2022": "*",    # bullet point
        "\xa0": " ",      # non-breaking space
        "\u2026": "...",  # ellipsis
    }
    for orig, rep in replacements.items():
        s = s.replace(orig, rep)

    clean = strip_emojis(s)
    if clean.strip().lower() in ("none", "null", "n/a", "na"):
        return ""
    return clean.encode("latin-1", "replace").decode("latin-1")


def make_pdf_label(text: Any, fallback: str = "Unknown") -> str:
    """Sanitize label, falling back to default string if empty."""
    res = make_pdf_safe(text)
    return res if res.strip() else fallback


def download_profile_pic(url: str) -> Optional[str]:
    """Download profile picture to a temporary file for PDF embedding."""
    if not url or not url.startswith("http"):
        return None
    try:
        temp_dir = tempfile.gettempdir()
        temp_path = os.path.join(temp_dir, f"profile_{os.urandom(4).hex()}.jpg")
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
            "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
            "Referer": "https://www.linkedin.com/",
        }
        response = requests.get(url, headers=headers, stream=True, timeout=10)
        response.raise_for_status()
        with open(temp_path, "wb") as f:
            for chunk in response.iter_content(1024):
                f.write(chunk)
        return temp_path
    except Exception as e:
        print(f"[PDF] Failed to download avatar from {url}: {e}")
        return None


class PDF(FPDF):
    """Custom branded PDF document with LinkedIn banner header and footer."""

    def header(self):
        # Top banner background
        self.set_fill_color(10, 102, 194)  # LinkedIn Blue (#0A66C2)
        self.rect(0, 0, 210, 32, "F")

        # Title text
        self.set_text_color(255, 255, 255)
        self.set_font("Arial", "B", 16)
        self.cell(0, 12, "PERSONA V3 — LINKEDIN PROFILE REPORT", ln=True, align="L")
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Persona V3 Intelligence System", 0, 0, "C")


def _pdf_section_header(pdf: FPDF, title: str):
    """Draw an underlined section header."""
    pdf.set_font("Arial", "B", 11)
    pdf.set_text_color(10, 102, 194)
    pdf.cell(0, 6, title, ln=True)
    pdf.set_fill_color(10, 102, 194)
    pdf.rect(15, pdf.get_y(), 180, 0.5, "F")
    pdf.ln(3)


def build_profile_pdf(pdf: FPDF, p: Dict[str, Any]):
    """Build a rich, structured profile page inside an FPDF document."""
    p = clean_profile(p)

    image_path = None
    pic_url = p.get("profile_picture", "")
    if pic_url and pic_url.startswith("http"):
        image_path = download_profile_pic(pic_url)

    pdf.set_y(38)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "B", 15)
    name_line = make_pdf_label(p.get("name", ""), fallback="Unknown Name")
    pdf.cell(130, 8, name_line, ln=True)

    headline = make_pdf_safe(p.get("headline", ""))
    if headline:
        pdf.set_font("Arial", size=10)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(130, 5, headline)
        pdf.ln(2)

    location = make_pdf_safe(p.get("location", ""))
    if location:
        pdf.set_font("Arial", size=9)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(130, 5, f"Location: {location}", ln=True)

    profile_url = make_pdf_safe(p.get("profile_url", ""))
    if profile_url:
        pdf.set_font("Arial", size=9)
        pdf.set_text_color(10, 102, 194)
        pdf.cell(130, 5, f"LinkedIn: {profile_url}", ln=True)

    connections = make_pdf_safe(str(p.get("connections", "")))
    if connections:
        pdf.set_font("Arial", size=9)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(130, 5, f"Connections: {connections}", ln=True)

    pdf.ln(3)

    if image_path:
        try:
            pdf.image(image_path, x=155, y=38, w=40, h=40)
            try:
                os.remove(image_path)
            except Exception:
                pass
        except Exception as e:
            print(f"[PDF] Error embedding image: {e}")

    current_y = pdf.get_y()
    if current_y < 82:
        pdf.set_y(82)

    # ── ABOUT ───────────────────────────────────────────────────────────────
    about_text = make_pdf_safe(p.get("about", ""))
    if about_text:
        _pdf_section_header(pdf, "ABOUT")
        pdf.set_font("Arial", size=9)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 5, about_text)
        pdf.ln(4)

    # ── CURRENT POSITION ───────────────────────────────────────────────────
    current_job = p.get("current_job")
    if current_job and isinstance(current_job, dict):
        job_title = make_pdf_safe(current_job.get("title", ""))
        job_company = make_pdf_safe(current_job.get("company", ""))
        job_dur = make_pdf_safe(current_job.get("duration", ""))
        if job_title or job_company:
            _pdf_section_header(pdf, "CURRENT POSITION")
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(0, 0, 0)
            pos_line = f"{job_title} at {job_company}" if (job_title and job_company) else (job_title or job_company)
            pdf.multi_cell(0, 5, pos_line)
            if job_dur:
                pdf.set_font("Arial", "I", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 5, job_dur, ln=True)
            pdf.ln(3)

    # ── EXPERIENCE ──────────────────────────────────────────────────────────
    exp_list = p.get("experiences") or p.get("experience") or []
    if exp_list:
        _pdf_section_header(pdf, "EXPERIENCE")
        for exp in exp_list:
            if not isinstance(exp, dict):
                continue
            title = make_pdf_safe(exp.get("title", ""))
            company = make_pdf_safe(exp.get("company", ""))
            duration = make_pdf_safe(exp.get("duration", ""))
            loc = make_pdf_safe(exp.get("location", ""))
            desc = make_pdf_safe(exp.get("description", ""))

            if not title and not company:
                continue

            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(0, 0, 0)
            pos_line = f"{title} at {company}" if (title and company) else (title or company)
            pdf.multi_cell(0, 5, pos_line)

            meta_parts = []
            if duration:
                meta_parts.append(duration)
            if loc:
                meta_parts.append(loc)
            if meta_parts:
                pdf.set_font("Arial", "I", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 5, "  ".join(meta_parts), ln=True)
            if desc:
                pdf.set_font("Arial", size=9)
                pdf.set_text_color(50, 50, 50)
                pdf.multi_cell(0, 4, desc)
            pdf.ln(2)
        pdf.ln(2)

    # ── EDUCATION & QUALIFICATIONS ──────────────────────────────────────────
    edu_list = p.get("education") or p.get("qualifications") or []
    if edu_list:
        _pdf_section_header(pdf, "EDUCATION & QUALIFICATIONS")
        for edu in edu_list:
            if not isinstance(edu, dict):
                continue
            inst = make_pdf_safe(edu.get("institution", ""))
            degree = make_pdf_safe(edu.get("degree", ""))
            dates = make_pdf_safe(edu.get("dates", ""))
            field = make_pdf_safe(edu.get("field_of_study", ""))

            if not inst and not degree:
                continue

            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(0, 0, 0)
            edu_line = inst if inst else ""
            if degree:
                edu_line += f" - {degree}" if edu_line else degree
            if field:
                edu_line += f", {field}"
            pdf.multi_cell(0, 5, edu_line)
            if dates:
                pdf.set_font("Arial", "I", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 5, dates, ln=True)
            pdf.ln(2)
        pdf.ln(2)

    # ── SKILLS ──────────────────────────────────────────────────────────────
    skills_list = p.get("skills") or []
    if skills_list:
        _pdf_section_header(pdf, "SKILLS")
        pdf.set_font("Arial", size=9)
        pdf.set_text_color(30, 30, 30)
        skills_formatted = []
        for s in skills_list:
            if isinstance(s, dict):
                skill_name = make_pdf_safe(s.get("skill") or s.get("name") or "")
                ends = make_pdf_safe(str(s.get("endorsements", "")))
                if skill_name:
                    skills_formatted.append(f"{skill_name} ({ends})" if ends and ends != "0" else skill_name)
            elif isinstance(s, str):
                safe_s = make_pdf_safe(s)
                if safe_s:
                    skills_formatted.append(safe_s)
        if skills_formatted:
            pdf.multi_cell(0, 5, make_pdf_safe(", ".join(skills_formatted)))
        pdf.ln(4)

    # ── CERTIFICATIONS ──────────────────────────────────────────────────────
    cert_list = p.get("certifications") or []
    if cert_list:
        _pdf_section_header(pdf, "CERTIFICATIONS")
        for cert in cert_list:
            if not isinstance(cert, dict):
                continue
            cname = make_pdf_safe(cert.get("name", ""))
            issuer = make_pdf_safe(cert.get("issuer", ""))
            date = make_pdf_safe(cert.get("date", ""))

            if not cname:
                continue

            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(0, 0, 0)
            cert_line = cname
            if issuer:
                cert_line += f" - {issuer}"
            pdf.cell(0, 5, cert_line, ln=True)
            if date:
                pdf.set_font("Arial", "I", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 4, date, ln=True)
            pdf.ln(2)
        pdf.ln(2)

    # ── LANGUAGES ───────────────────────────────────────────────────────────
    lang_list = p.get("languages") or []
    if lang_list:
        _pdf_section_header(pdf, "LANGUAGES")
        pdf.set_font("Arial", size=9)
        pdf.set_text_color(30, 30, 30)
        langs_formatted = []
        for l in lang_list:
            if isinstance(l, dict):
                lang_name = make_pdf_safe(l.get("language", ""))
                prof = make_pdf_safe(l.get("proficiency", ""))
                if lang_name:
                    langs_formatted.append(f"{lang_name} ({prof})" if prof else lang_name)
            elif isinstance(l, str):
                safe_l = make_pdf_safe(l)
                if safe_l:
                    langs_formatted.append(safe_l)
        if langs_formatted:
            pdf.multi_cell(0, 5, make_pdf_safe(", ".join(langs_formatted)))
        pdf.ln(4)

    # ── VOLUNTEER EXPERIENCE ────────────────────────────────────────────────
    vol_list = p.get("volunteer") or []
    if vol_list:
        _pdf_section_header(pdf, "VOLUNTEER EXPERIENCE")
        for vol in vol_list:
            if not isinstance(vol, dict):
                continue
            role = make_pdf_safe(vol.get("role", ""))
            org = make_pdf_safe(vol.get("organization", ""))
            dur = make_pdf_safe(vol.get("duration", ""))
            if not role and not org:
                continue
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(0, 0, 0)
            vol_line = f"{role} at {org}" if (role and org) else (role or org)
            pdf.multi_cell(0, 5, vol_line)
            if dur:
                pdf.set_font("Arial", "I", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 5, dur, ln=True)
            pdf.ln(2)
        pdf.ln(2)

    # ── HONORS & AWARDS ─────────────────────────────────────────────────────
    hon_list = p.get("honors") or []
    if hon_list:
        _pdf_section_header(pdf, "HONORS & AWARDS")
        for hon in hon_list:
            if not isinstance(hon, dict):
                continue
            title = make_pdf_safe(hon.get("title", ""))
            issuer = make_pdf_safe(hon.get("issuer", ""))
            date = make_pdf_safe(hon.get("date", ""))
            if not title:
                continue
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(0, 0, 0)
            hon_line = title
            if issuer:
                hon_line += f" - {issuer}"
            pdf.multi_cell(0, 5, hon_line)
            if date:
                pdf.set_font("Arial", "I", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 4, date, ln=True)
            pdf.ln(2)
        pdf.ln(2)

    # ── RECOMMENDATIONS ─────────────────────────────────────────────────────
    rec_list = p.get("recommendations") or []
    if rec_list:
        _pdf_section_header(pdf, "RECOMMENDATIONS")
        for rec in rec_list:
            if not isinstance(rec, dict):
                continue
            recommender = make_pdf_safe(rec.get("recommender", ""))
            rec_title = make_pdf_safe(rec.get("title", ""))
            text_val = make_pdf_safe(rec.get("text", ""))
            if not recommender and not text_val:
                continue
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(0, 0, 0)
            rec_header = recommender
            if rec_title:
                rec_header += f" ({rec_title})"
            if rec_header:
                pdf.cell(0, 5, rec_header, ln=True)
            if text_val:
                pdf.set_font("Arial", "I", 9)
                pdf.set_text_color(50, 50, 50)
                pdf.multi_cell(0, 4, text_val)
            pdf.ln(2)
        pdf.ln(2)


def generate_profile_pdf(profile: Dict[str, Any], output_path: Path) -> Path:
    """Generate a single-profile PDF report file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf = PDF()
    pdf.set_margins(15, 38, 15)
    pdf.set_auto_page_break(True, margin=15)
    pdf.add_page()
    build_profile_pdf(pdf, profile)
    pdf.output(str(output_path))
    return output_path


def generate_bulk_pdf(profiles: List[Dict[str, Any]], output_path: Path) -> Path:
    """Generate a multi-profile consolidated PDF report file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf = PDF()
    pdf.set_margins(15, 38, 15)
    pdf.set_auto_page_break(True, margin=15)
    for p in profiles:
        pdf.add_page()
        build_profile_pdf(pdf, p)
    pdf.output(str(output_path))
    return output_path


def generate_text_pdf(text: str, output_path: Path) -> Path:
    """Generate a clean text PDF file from raw string content."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=10)
    for line in text.split("\n"):
        safe_line = line.encode("latin-1", "replace").decode("latin-1")
        pdf.cell(0, 5, safe_line, ln=True)
    pdf.output(str(output_path))
    return output_path
